### ISSUE TITLE
Little talk about adding recipes.

### ISSUE THREAD

**Issue by emilhotkowski** [rjiuk3566/Pindish#12]
Ok so i've checked and written some methods for Recipe Parser and i have to say that i won't be ideal, and it is really hard and not-time-worth to create universal parser, so i came up with an interesting idea of how to add recipe on our site : 

1) We click that add button/ card (we).
2) Pop-up shows.
    Something like : **Put your recipe link here [ ------------ ]** , well desinged ofc.
3) We parse site with parser to take as much information as we can (it takes 2-3 seconds) [We could make a window with message : _please wait few seconds_]
4) Then pop-up changes to one with few areas filled with parsed data. This is editable so you can fix issues with empty (not parsed data) , with poor formatted text and so on.
Once you are happy with the look and information on your recipe, you save it (it is permanent, you cannot change it) [every change will be made with out note system]
GG - parser problem solved.

**Comment by piotrek-b** [comment]
Nice. Looking forward to write some code!
